/*
 * Copyright (C) 2016 thedathoudarya
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.clough.android.adbv.view;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author thedathoudarya
 */
public class HistoryItemPanel extends javax.swing.JPanel {

    private final int historyIndex;
    private final boolean queryFromConnectedApplication;
    private final String query;
    private final JTextArea queryingTextArea;

    /**
     * Creates new form TestPanel
     */
    public HistoryItemPanel(int historyIndex, boolean queryFromConnectedApplication, String query, JTextArea queryingTextArea) {
        initComponents();
        this.historyIndex = historyIndex;
        this.queryFromConnectedApplication = queryFromConnectedApplication;
        this.query = query;
        this.queryingTextArea = queryingTextArea;
        decorateHistoryItem();
    }

    private void decorateHistoryItem() {
        historyIndexLabel.setText(String.valueOf(historyIndex));
        queryLabel.setText(query.replaceAll("\n", " "));
        Color color;
        if (queryFromConnectedApplication) {
            color = new Color(0, 0, 0);
        } else {
            color = new Color(100, 100, 100);
        }
        historyIndexLabel.setForeground(color);
        queryLabel.setForeground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyIndexLabel = new javax.swing.JLabel();
        queryLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        historyIndexLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        historyIndexLabel.setText("999");
        historyIndexLabel.setPreferredSize(new java.awt.Dimension(20, 20));

        queryLabel.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        queryLabel.setText("select * from `test_table` where `test_f0` = '123' and...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(historyIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addComponent(queryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            queryingTextArea.setText(query);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel historyIndexLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel queryLabel;
    // End of variables declaration//GEN-END:variables
}
